# 端口号，默认8080
server:
  port: 8080

#  命名以及数据库连接。
spring:
  application:
    name: springboot_project

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# 映射地址 和 实体类
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboot_project.model